version: 2.1


jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:lts-stretch

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
            name: Running tests
            command: npm test

  deploy-calculator:
    working_directory: ~/project
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Installing Deployment Dependencies
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Deploying Production Environment
          command: eb deploy ProdCalculatorApi-env         

workflows:
  deploy:
    jobs:
      - deploy-calculator:
          filters:
            branches:
              only: main
